In [1]:
import yfinance as yf

In [3]:
stock = yf.download("RELIANCE.NS", start="2015-01-01", end="2024-12-31")
index = yf.download("^NSEI", start = "2015-01-01", end="2024-12-31")

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [4]:
stock.head()

Price            Close        High         Low        Open      Volume
Ticker     RELIANCE.NS RELIANCE.NS RELIANCE.NS RELIANCE.NS RELIANCE.NS
Date
2015-01-01  189.125351  189.998667  188.220086  188.784556     2963643
2015-01-02  188.624817  190.861356  188.358571  189.167973     7331366
2015-01-05  186.558685  189.764389  186.185926  188.507664    10103941
2015-01-06  178.091827  185.951642  177.218511  185.312637    18627980
2015-01-07  181.968491  182.927005  178.283544  178.304843    20720312

In [5]:
import pandas as pd

stock_ret = stock["Close"].pct_change().dropna()
index_ret = index["Close"].pct_change().dropna()

df = pd.concat([stock_ret,index_ret], axis=1, join="inner")
df.columns = ["stock_ret", "index_ret"]
df.head()

            stock_ret  index_ret
Date
2015-01-05  -0.010954  -0.002031
2015-01-06  -0.045384  -0.029964
2015-01-07   0.021768  -0.003107
2015-01-08  -0.014339   0.016354
2015-01-09   0.021673   0.006060

In [10]:
import numpy as np

import statsmodels.api as sm

cov = np.cov(df["stock_ret"], df["index_ret"])[0][1]
var = np.var(df["index_ret"])
beta_manual = cov/var

print("Beta (Covariance Method):", beta_manual)

Beta (Covariance Method): 1.0959498246815906

In [11]:
X = sm.add_constant(df["index_ret"])
model = sm.OLS(df["stock_ret"], X).fit()
print(model.summary())
print("Beta (OLS): ", model.params["index_ret"])

                            OLS Regression Results
==============================================================================
Dep. Variable:              stock_ret   R-squared:                       0.429
Model:                            OLS   Adj. R-squared:                  0.429
Method:                 Least Squares   F-statistic:                     1843.
Date:                Thu, 02 Jul 2026   Prob (F-statistic):          7.15e-301
Time:                        16:07:52   Log-Likelihood:                 7137.4
No. Observations:                2457   AIC:                        -1.427e+04
Df Residuals:                    2455   BIC:                        -1.426e+04
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0004      0.000      1.412      0.158      -0.000       0.001
index_ret      1.0955      0.026     42.929      0.000       1.045       1.146
==============================================================================
Omnibus:                      553.110   Durbin-Watson:                   1.933
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             5690.030
Skew:                           0.761   Prob(JB):                         0.00
Kurtosis:                      10.298   Cond. No.                         95.4
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
Beta (OLS):  1.0955037726568944